apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pipeline5-ingress
  namespace: abc-bank
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: abc.local
    http:
      paths:

      - path: /
        pathType: Prefix
        backend:
          service:
            name: pipeline5-service
            port:
              number: 80

      - path: /login
        pathType: Prefix
        backend:
          service:
            name: pipeline5-service
            port:
              number: 80

      - path: /signup
        pathType: Prefix
        backend:
          service:
            name: pipeline5-service
            port:
              number: 80

